// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmaWeb.Data;

#nullable disable

namespace PharmaWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251207074047_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PharmaWeb.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaCtdh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaCTDH");

                    b.Property<string>("CachDung")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DonGia")
                        .HasColumnType("REAL");

                    b.Property<int?>("MaDh")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaDH");

                    b.Property<int?>("MaThuoc")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaCtdh");

                    b.HasIndex("MaDh");

                    b.HasIndex("MaThuoc");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("PharmaWeb.Models.DonHang", b =>
                {
                    b.Property<int>("MaDh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaDH");

                    b.Property<string>("AnhDonThuoc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiaChiGiaoHang")
                        .HasColumnType("TEXT");

                    b.Property<string>("GhiChu")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaDs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaDS");

                    b.Property<int?>("MaKh")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaKH");

                    b.Property<DateOnly?>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<double?>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Chờ xác nhận");

                    b.HasKey("MaDh");

                    b.HasIndex("MaDs");

                    b.HasIndex("MaKh");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("PharmaWeb.Models.DuocSi", b =>
                {
                    b.Property<int>("MaDs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaDS");

                    b.Property<string>("DienThoai")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaTk")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaTK");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoChungChi")
                        .HasColumnType("TEXT");

                    b.HasKey("MaDs");

                    b.HasIndex("MaTk");

                    b.ToTable("DuocSi", (string)null);
                });

            modelBuilder.Entity("PharmaWeb.Models.GioHang", b =>
                {
                    b.Property<int>("MaGh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaGH");

                    b.Property<int?>("MaTk")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaTK");

                    b.Property<string>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("MaGh");

                    b.HasIndex("MaTk");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("PharmaWeb.Models.GioHangChiTiet", b =>
                {
                    b.Property<int>("MaGhct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaGHCT");

                    b.Property<int?>("MaGh")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaGH");

                    b.Property<int?>("MaThuoc")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaGhct");

                    b.HasIndex("MaGh");

                    b.HasIndex("MaThuoc");

                    b.ToTable("GioHangChiTiet", (string)null);
                });

            modelBuilder.Entity("PharmaWeb.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaKH");

                    b.Property<string>("DiaChi")
                        .HasColumnType("TEXT");

                    b.Property<string>("DienThoai")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaTk")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaTK");

                    b.HasKey("MaKh");

                    b.HasIndex("MaTk");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("PharmaWeb.Models.LienHe", b =>
                {
                    b.Property<int>("MaLienHe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("TEXT");

                    b.Property<string>("TieuDe")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Chưa xử lý");

                    b.HasKey("MaLienHe");

                    b.ToTable("LienHe", (string)null);
                });

            modelBuilder.Entity("PharmaWeb.Models.LoaiThuoc", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MoTa")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenLoai")
                        .HasColumnType("TEXT");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiThuoc", (string)null);
                });

            modelBuilder.Entity("PharmaWeb.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaTK");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaTk");

                    b.HasIndex(new[] { "TenDangNhap" }, "IX_TaiKhoan_TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("PharmaWeb.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaTt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaTT");

                    b.Property<int?>("MaDh")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaDH");

                    b.Property<string>("NgayThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PhuongThuc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SoTien")
                        .HasColumnType("REAL");

                    b.HasKey("MaTt");

                    b.HasIndex("MaDh");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("PharmaWeb.Models.Thuoc", b =>
                {
                    b.Property<int>("MaThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Anh")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CanKeDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("DangBaoChe")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Gia")
                        .HasColumnType("REAL");

                    b.Property<string>("HamLuong")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("HanSuDung")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoatChat")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaLoai")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MoTa")
                        .HasColumnType("TEXT");

                    b.Property<string>("NhaSanXuat")
                        .HasColumnType("TEXT");

                    b.Property<string>("NuocSanXuat")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDangKy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenThuoc")
                        .HasColumnType("TEXT");

                    b.HasKey("MaThuoc");

                    b.HasIndex("MaLoai");

                    b.ToTable("Thuoc", (string)null);
                });

            modelBuilder.Entity("PharmaWeb.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("PharmaWeb.Models.DonHang", "MaDhNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDh");

                    b.HasOne("PharmaWeb.Models.Thuoc", "MaThuocNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaThuoc");

                    b.Navigation("MaDhNavigation");

                    b.Navigation("MaThuocNavigation");
                });

            modelBuilder.Entity("PharmaWeb.Models.DonHang", b =>
                {
                    b.HasOne("PharmaWeb.Models.DuocSi", "MaDsNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaDs");

                    b.HasOne("PharmaWeb.Models.KhachHang", "MaKhNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKh");

                    b.Navigation("MaDsNavigation");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("PharmaWeb.Models.DuocSi", b =>
                {
                    b.HasOne("PharmaWeb.Models.TaiKhoan", "MaTkNavigation")
                        .WithMany("DuocSis")
                        .HasForeignKey("MaTk");

                    b.Navigation("MaTkNavigation");
                });

            modelBuilder.Entity("PharmaWeb.Models.GioHang", b =>
                {
                    b.HasOne("PharmaWeb.Models.TaiKhoan", "MaTkNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaTk");

                    b.Navigation("MaTkNavigation");
                });

            modelBuilder.Entity("PharmaWeb.Models.GioHangChiTiet", b =>
                {
                    b.HasOne("PharmaWeb.Models.GioHang", "MaGhNavigation")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("MaGh");

                    b.HasOne("PharmaWeb.Models.Thuoc", "MaThuocNavigation")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("MaThuoc");

                    b.Navigation("MaGhNavigation");

                    b.Navigation("MaThuocNavigation");
                });

            modelBuilder.Entity("PharmaWeb.Models.KhachHang", b =>
                {
                    b.HasOne("PharmaWeb.Models.TaiKhoan", "MaTkNavigation")
                        .WithMany("KhachHangs")
                        .HasForeignKey("MaTk");

                    b.Navigation("MaTkNavigation");
                });

            modelBuilder.Entity("PharmaWeb.Models.ThanhToan", b =>
                {
                    b.HasOne("PharmaWeb.Models.DonHang", "MaDhNavigation")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaDh");

                    b.Navigation("MaDhNavigation");
                });

            modelBuilder.Entity("PharmaWeb.Models.Thuoc", b =>
                {
                    b.HasOne("PharmaWeb.Models.LoaiThuoc", "MaLoaiNavigation")
                        .WithMany("Thuocs")
                        .HasForeignKey("MaLoai");

                    b.Navigation("MaLoaiNavigation");
                });

            modelBuilder.Entity("PharmaWeb.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("PharmaWeb.Models.DuocSi", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("PharmaWeb.Models.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("PharmaWeb.Models.KhachHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("PharmaWeb.Models.LoaiThuoc", b =>
                {
                    b.Navigation("Thuocs");
                });

            modelBuilder.Entity("PharmaWeb.Models.TaiKhoan", b =>
                {
                    b.Navigation("DuocSis");

                    b.Navigation("GioHangs");

                    b.Navigation("KhachHangs");
                });

            modelBuilder.Entity("PharmaWeb.Models.Thuoc", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("GioHangChiTiets");
                });
#pragma warning restore 612, 618
        }
    }
}
